### ISSUE TITLE
meta/commander.js is not downloadable

### ISSUE THREAD

**Issue by valdestrijus** [mateodelnorte/meta#46] opened 2018-10-01 07:39 UTC
if i use this library behind proxy, where npm registry is some sort of artifactory I can not install meta via
`npm install meta -g` because there is some script that is loaded from github not from registry.

```shell
npm install meta -g
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t ssh://git@github.com/mateodelnorte/commander.js.git
npm ERR!
npm ERR! ssh: connect to host github.com port 22: Connection refused
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users...\\2018-10-01T07_15_23_818Z-debug.log
```

Consider putting commander.js as npm package instead so that everyone behind proxy can also use your meta tool.

**Comment by mateodelnorte** [comment] 2018-10-02 16:38
If I were to guess, your npm or git setup is incorrect. We use Sonatype Nexus (main competitor to artifactory) at my work, and we use meta extensively. 

We can't just use the main commander.js package because it's broken on windows. My PR with them https://github.com/tj/commander.js/pull/604 fixes that. If you want to help call attention to that PR so that it can get merged, that might help you fix your problem. 

I don't think the issue is with meta, however. Do you have ssh keys correctly uploaded to GitHub?

**Closed** 2018-11-03 15:53 UTC
