### ISSUE TITLE
order of parameters get mixed up

### ISSUE THREAD

**Issue by ThomasPinna** [mateodelnorte/meta#191] opened 2019-09-25 12:55 UTC
## 🐛 Bug Report

With longer meta git commands, the order of parameters might get mixed up, resulting in errors.

## To Reproduce

Run a command like 

`meta git push --set-upstream origin images_in_app`

It will for each repository try and run

`git push images_in_app --set-upstream origin` (resulting in an error)

## Expected behavior

It should run the following command in each repository

`git push --set-upstream origin images_in_app`

## Temporary workaround for people with a similar issue

`meta git push "--set-upstream origin images_in_app"`
--> but this seems a bit annoying imho

**Comment by mateodelnorte** [comment] 2019-09-25 15:20
Interesting. Any chance you can try and pinpoint where this is happening in code, or perhaps make a PR? This will be in https://github.com/mateodelnorte/meta-git.

**Comment by ThomasPinna** [comment] 2019-09-26 14:44
I have looked around a little bit and the issue does not seem to be in  https://github.com/mateodelnorte/meta-git (it already receives the argv in a scrambled order)

it happens in commander in `index.js` of this repository. I'm not sure I can tell you how to fix it (you have a fork of commander with some changes, it seems), but if you `console.log(program)` in the end of the `run(cwd, argv)` function, you can see the following:

```javascript
{
 ...
 rawArgs:
   [ '/usr/local/Cellar/node/12.3.1/bin/node',
     '/Users/thomaspinna/Documents/repositories/meta/bin/meta',
     'git',
     'push',
     '--set-upstream',
     'origin',
     'images_in_app' ],
  args: [ 'git', 'push', 'images_in_app' ],
  runningCommand:
   ChildProcess {
     _events:
      [Object: null prototype] { close: [Function: bound exit], error: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _closesNeeded: 1,
     _closesGot: 0,
     connected: false,
     signalCode: null,
     exitCode: null,
     killed: false,
     spawnfile: 'meta-git',
     _handle: Process { onexit: [Function], [Symbol(owner)]: [Circular] },
     spawnargs:
      [ 'meta-git', 'push', 'images_in_app', '--set-upstream', 'origin' ],
     pid: undefined,
     stdin: null,
     stdout: null,
     stderr: null,
     stdio: [ null, null, null ] } }
```

you might notice that the `rawArgs` are still correct, but the `spawnargs` of the childprocess are already wrong.

There is an open issue on [commander.js](https://github.com/tj/commander.js/issues/508) that might be related

**Comment by mateodelnorte** [comment] 2019-09-26 14:54
Interesting. Looks like the issue is in Commander. Perhaps I can update our
fork form master and see what fixes we get.

Otherwise, this might support others' idea to move away from Commander.

**Comment by patrickleet** [comment] 2019-11-01 18:52
as a workaround, fyi, `meta exec "command"` might do it for you

**Closed** 2020-01-07 20:25 UTC
Labels: bug, wontfix
